#!/usr/bin/env python

# Copyright (c) 2011, Willow Garage, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the Willow Garage, Inc. nor the names of its
#      contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import rospy
import time
import math
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from tf.transformations import euler_from_quaternion
from sensor_msgs.msg import Illuminance
from sensor_msgs.msg import LaserScan
import sys, select, os
if os.name == 'nt':
  import msvcrt
else:
  import tty, termios




left =0
right =0
pose_x = 0
pose_y = 0
phi = 0
READ_TIME = 0
msg = """
Control Your TurtleBot3!
---------------------------
Moving around:
        w
   a    s    d
        x
w/x : increase/decrease linear velocity (Burger : ~ 0.22, Waffle and Waffle Pi : ~ 0.26)
a/d : increase/decrease angular velocity (Burger : ~ 2.84, Waffle and Waffle Pi : ~ 1.82)
space key, s : force stop
CTRL-C to quit
"""

e = """
Communications Failed
"""

def getKey():
    if os.name == 'nt':
      return msvcrt.getch()

    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key



def callbackone(data):
    global right
    right = data.illuminance



def callbacktwo(data):
    global left
    left = data.illuminance
def callback_update_position(data):
    global pose_x
    global pose_y
    global phi
    pose_x = round(data.pose.pose.position.x, 4)
    pose_y = round(data.pose.pose.position.y, 4)
    quaternion = data.pose.pose.orientation
    orientation_list = [quaternion.x, quaternion.y, quaternion.z, quaternion.w]
    (roll, pitch, yaw) = euler_from_quaternion(orientation_list)
    phi = yaw
    # yaw_deg = round(math.degrees(yaw), 4)
    # print("WEIZHI:",pose_x,pose_y)

    # print("rest:", orientation_list, yaw_deg)
def callLaser(data):
    print(data)
if __name__=="__main__":
    if os.name != 'nt':
        settings = termios.tcgetattr(sys.stdin)

    rospy.init_node('topic_subscriber')
    pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)
    Kp = 5
    stepDegree = 360
    turtlebot3_model = rospy.get_param("model", "burger")

    status = 0
    target_linear_vel   = 0.0
    target_angular_vel  = 0.0
    control_linear_vel  = 0.0
    control_angular_vel = 0.0
    twist = Twist()

    # control_linear_vel = makeSimpleProfile(control_linear_vel, target_linear_vel, (LIN_VEL_STEP_SIZE/2.0))
    control_linear_vel = 0.0
    twist.linear.x = control_linear_vel;
    twist.linear.y = 0.0;
    twist.linear.z = 0.0

    # control_angular_vel = makeSimpleProfile(control_angular_vel, target_angular_vel, (ANG_VEL_STEP_SIZE/2.0))
    control_angular_vel = 0.0
    twist.angular.x = 0.0;
    twist.angular.y = 0.0;
    twist.angular.z = control_angular_vel

    pub.publish(twist)
    # time.sleep(0.1)
    angPosStep = 1e-3
    Kp = 0.0013
    Kd = 0.00006
    Tp = 0.06
    prevErr = 0
    derivative = 0
    desAngPos = 0
    timep =0
    try:
        print(msg)
        while(1):
            sub = rospy.Subscriber('/light_sensor_plugin/lightSensor', Illuminance, callbackone)
            sub2 = rospy.Subscriber('/light_sensor_plugin/leftLightSensor', Illuminance, callbacktwo)
            sub3 = rospy.Subscriber("odom", Odometry, callback_update_position)
            sub4 = rospy.Subscriber("/scan", LaserScan, callLaser)
            target_linear_vel = Tp
            if(right < left-20):

                target_linear_vel = 0.0
                # target_angular_vel = -0.2
                # print( target_angular_vel , phi)
                # print(pose_x, pose_y, yaw_deg)
                print("turn Right !!! W-_-W")
            elif(left == 201.0 and  right == 201.0):
                target_linear_vel = -Tp
                # print(pose_x, pose_y, yaw_deg)
                print("DaoChe")
            elif(left < right-20):

                target_linear_vel = 0.0

                # target_angular_vel = 0.2
                # print( target_angular_vel , phi)
                # print(pose_x, pose_y, yaw_deg)
                print("turn left !!! //A_A//")
            # elif(left == right):
            #     target_linear_vel = Tp
            #     target_angular_vel = 0.0
            #     # print(pose_x, pose_y, yaw_deg)
            #
            #     print("perfect !!!")
            error = right - left
            t = time.time()
            dt = t- timep
            derivative = (error - prevErr)/dt
            timep = t
            print (derivative)

            target_angular_vel = Kp*error + Kd*derivative

            print(target_angular_vel)
            print(Kd*derivative)
            print("-----------------------------------------------------------------")
            # print(target_angular_vel,Kp*error, Kd*derivative)
            prevErr = error
            key = getKey()
            if key == ' ' or key == 's':
                target_linear_vel = 0.0
                control_linear_vel = 0.0
                target_angular_vel = 0.0
                control_angular_vel = 0.0
            else:
                if (key == '\x03'):
                    break
            twist = Twist()

            # control_linear_vel = makeSimpleProfile(control_linear_vel, target_linear_vel, (LIN_VEL_STEP_SIZE/2.0))
            control_linear_vel = target_linear_vel
            twist.linear.x = control_linear_vel; twist.linear.y = 0.0; twist.linear.z = 0.0

            # control_angular_vel = makeSimpleProfile(control_angular_vel, target_angular_vel, (ANG_VEL_STEP_SIZE/2.0))
            control_angular_vel = target_angular_vel
            twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = control_angular_vel

            pub.publish(twist)
            # time.sleep(dt)

            time.sleep(0.1)

    except:
        print(e)

    finally:
        twist = Twist()
        twist.linear.x = 0.0; twist.linear.y = 0.0; twist.linear.z = 0.0
        twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = 0.0
        pub.publish(twist)

    if os.name != 'nt':
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)